### ISSUE TITLE
Provide Docker image for easy local development set-up

### ISSUE THREAD

**Issue by cmichi** [paritytech/cumulus#1004]
We should reduce friction of setting up a local instance of Canvas. 

Right now we recommend using [`substrate-contracts-node`](https://github.com/paritytech/substrate-contracts-node) for the local development of contracts for Canvas. We should have an easy possibility of developing locally for Canvas though, as this will be closer to the environment in which the contract will eventually run.

## ToDo

- [ ] Create a Dockerfile for Canvas (in the `scripts` repository [here](https://github.com/paritytech/scripts/tree/master/dockerfiles)).
- [ ] The Dockerfile should contain the latest compatible build of Polkadot, Canvas, `polkadot-launch` and our `polkadot-launch` [`config.json`](https://github.com/paritytech/canvas/blob/master/polkadot-launch/config.json).
- [ ] Create an issue in the [devops](https://github.com/paritytech/ci_cd/issues) repo for them to set up a nightly schedule to build and publish the Docker image.
- [ ] Add readme instructions how to pull the image and start it with port bindings to the local machine, so that you can just open a UI.
- [ ] Switch the Dockerfile used in the `.gitlab-ci.yml` to the new one.

**Comment by cmichi** [comment]
No longer relevant.
