### ISSUE TITLE
Cumulus polkadot-v0.9.18 collator binary Release checklist

### ISSUE THREAD

**Issue by chevdor** [paritytech/cumulus#1115]
The release of binary / runtime being now split, this is the first checklist for the binary part of the release.

----

# Release Checklist (Binary)

- [x] Check that the new polkadot-collator versions have run  without issue on:
   - [x] Westmint ([new request](https://github.com/paritytech/devops/issues/new?assignees=&labels=awaiting+priority%2C+new+deployment%2C+burn-in&template=deployment_request.md&title=Burn-in%20Request%20for%20Westmint))
   - [x] Statemine ([new request](https://github.com/paritytech/devops/issues/new?assignees=&labels=awaiting+priority%2C+new+deployment%2C+burn-in&template=deployment_request.md&title=Burn-in%20Request%20for%20Statemint))
   - [x] Statemint ([new request](https://github.com/paritytech/devops/issues/new?assignees=&labels=awaiting+priority%2C+new+deployment%2C+burn-in&template=deployment_request.md&title=Burn-in%20Request%20for%20Statemine))

    
- [x] Check that a draft release has been created at
    https://github.com/paritytech/cumulus/releases with relevant [release
    notes](#release-notes).
- [x] Check that [build artifacts](#build-artifacts) have been added to the
    draft-release.

---

### Burn In

Ensure that Parity DevOps has run the new release on Westmint and Statemine collators for 12h prior to publishing the release.

### Build Artifacts

Add any necessary assets to the release. They should include:

- Linux binary
- GPG signature of the Linux binary
- SHA256 of binary
- Source code

### Release notes

The release notes should list:

- The priority of the release (i.e., how quickly users should upgrade) - this is
    based on the max priority of any *client* changes.
- Which native runtimes and their versions are included
- The proposal hashes of the runtimes as built with
    [srtool](https://github.com/paritytech/srtool)
- Any changes in this release that are still awaiting audit

The release notes may also list:

- Free text at the beginning of the notes mentioning anything important
    regarding this release
- Notable changes separated into sections.

**Comment by chevdor** [comment]
ref https://github.com/paritytech/devops/issues/1522

**Comment by chevdor** [comment]
ref https://github.com/paritytech/cumulus/releases/tag/polkadot-v0.9.18
