### ISSUE TITLE
Cumulus polkadot-v0.9.19 collator binary Release checklist 

### ISSUE THREAD

**Issue by chevdor** [paritytech/cumulus#1201]
The release of binary / runtime being now split, this is the first checklist for the binary part of the release.
You may also want to have a look at the [runtime checklist](https://github.com/paritytech/cumulus/issues/1189).

----

# Release Checklist (Binary)

- [x] Check that the new polkadot-collator versions have run  without issue on:
   - [x] Westmint ([request](https://github.com/paritytech/devops/issues/1590))
   - [x] Statemine ([request](https://github.com/paritytech/devops/issues/1591))
   - [x] Statemint ([request](https://github.com/paritytech/devops/issues/1592))

    
- [x] Check that a draft release has been created at
    https://github.com/paritytech/cumulus/releases with relevant [release
    notes](#release-notes).
- [x] Check that [build artifacts](#build-artifacts) have been added to the
    draft-release.

---

### Burn In

Ensure that Parity DevOps has run the new release on Westmint and Statemine collators for 12h prior to publishing the release.

### Build Artifacts

Add any necessary assets to the release. They should include:

- Linux binary
- GPG signature of the Linux binary
- SHA256 of binary
- Source code

### Release notes

The release notes should list:

- The priority of the release (i.e., how quickly users should upgrade) - this is
    based on the max priority of any *client* changes.
- Which native runtimes and their versions are included
- The proposal hashes of the runtimes as built with
    [srtool](https://github.com/paritytech/srtool)
- Any changes in this release that are still awaiting audit

The release notes may also list:

- Free text at the beginning of the notes mentioning anything important
    regarding this release
- Notable changes separated into sections.

**Comment by chevdor** [comment]
The burn-ins did run successfully. The logs showed however a slightly higher number of **WARN**ings than expected. The issue has been fixed in https://github.com/paritytech/polkadot/pull/5404 and currently generate in around 1000 WARN per day. SInce those are easy to filter out, the release is not blocked and the amount of WARN will be reduced in the next release.

**Comment by chevdor** [comment]
This version has been released.
