### ISSUE TITLE
Release Checklist - Client v0.9.220

### ISSUE THREAD

**Issue by chevdor** [paritytech/cumulus#1295]
For the runtime, see #1288 

----

# Release Checklist (Binary)

- [ ] Check that the new `polkadot-parachain` versions have run  without issue on ([requests](https://github.com/paritytech/devops/issues?q=is%3Aissue+is%3Aopen+label%3Aburn-in+220-rc2)):
   - [ ] Westmint - [request](https://github.com/paritytech/devops/issues/1693)
   - [ ] Statemine - [request](https://github.com/paritytech/devops/issues/1694)
   - [ ] Statemint - [request](https://github.com/paritytech/devops/issues/1695)

- [x] Check that a release has been created at
    https://github.com/paritytech/cumulus/releases with relevant [release
    notes](#release-notes).
- [ ] Check that [build artifacts](#build-artifacts) have been added to the
    release.

---

### Burn In

Ensure that Parity DevOps has run the new release on Westmint and Statemine collators for 12h prior to publishing the release.

### Build Artifacts

Add any necessary assets to the release. They should include:

- Linux binary
- GPG signature of the Linux binary
- SHA256 of binary
- Source code

**Comment by chevdor** [comment]
This release is superseded by 0.9.230
