### ISSUE TITLE
Release Checklist - Parachains v9270

### ISSUE THREAD

**Issue by chevdor** [paritytech/cumulus#1512]
# Release Checklist - Runtimes

See also #1511

### Codebase
These checks should be performed on the codebase.

- [x] the [`spec_version`](../../docs/release.md#spec-version) has been incremented since the
    last release for any native runtimes from any existing use on public (non-private/test) networks @bkontur 
- [x] previously [completed migrations](../../docs/release.md#old-migrations-removed) are @muharem 
    removed for any public (non-private/test) networks
- [x] No migrations added in the last release that would need to be added @muharem 
- [x] pallet and [extrinsic ordering](../../docs/release.md#extrinsic-ordering) as well as `SignedExtension`s have stayed
    the same. Bump `transaction_version` otherwise @bkontur 
- [x] the [benchmarks](https://github.com/paritytech/ci_cd/wiki/Benchmarks:-cumulus) ran @ruseinov 
- [x] the weights have been updated for any modified runtime logic @ruseinov 
- [x] the various pieces of XCM config are sane @muharem 

### On the release branch

The following checks can be performed after we have forked off to the release-
candidate branch or started an additional release candidate branch (rc-2, rc-3, etc)

- [x] Verify [new migrations](../../docs/release.md#new-migrations) complete successfully, and the
    runtime state is correctly updated for any public (non-private/test)
    networks @muharem 
- [x] Run [integration tests](https://github.com/paritytech/parachains-integration-tests/) @ruseinov 
Until https://github.com/paritytech/ci_cd/issues/499 is done, tests will have to be run manually.
1. Go to https://github.com/paritytech/parachains-integration-tests and checkout to the release branch.
E.g. https://github.com/paritytech/parachains-integration-tests/tree/release-v9270-v0.9.27
for `release-parachains-v0.9.270`
2. Clone `release-parachains-<version>` branch from Cumulus
3. `cargo build --release`
4. Copy `./target/polkadot-parachain` to `./bin`
5. Clone `it/release-<version>-fast-sudo` from Polkadot
6. `cargo build --release`
7. Copy `./target/polkadot` into `./bin` (in Cumulus)
8. Run the tests:
	- Statemint: `yarn zombienet-test -c ./examples/statemint/config.toml -t ./examples/statemint`
	- Statemine: `yarn zombienet-test -c ./examples/statemine/config.toml -t ./examples/statemine`

- [x] Push runtime upgrade to Westmint and verify network stability @bkontur 

### Github

- [x] Check that a draft release has been created at the [Github Releases page](https://github.com/paritytech/cumulus/releases) with relevant [release
    notes](../../docs/release.md#release-notes)
- [x] Check that [build artifacts](../../docs/release.md#build-artifacts) have been added to the
    draft-release.

---

Read more about the [release documentation](../../docs/release.md).

**Comment by EgorPopelyaev** [comment]
Metadata comparison:
Date: Mon Aug  8 12:41:53 UTC 2022
Reference: wss://statemine-rpc.polkadot.io
Target version: $BIN 0.9.270-38920db7b81
Chain: statemine-local
----------------------------------------------------------------------
              [Spec] name: statemine
                     spec_version: 9230 -> 9270
                     transaction_version: 7
          [Metadata] version: 14
           [Modules] num: 21
                          [System] idx: 0 (calls: 9, storage: 17)
                 [ParachainSystem] idx: 1 (calls: 4, storage: 21 -> 22)
                                   [+] storage: lastRelayChainBlockNumber
                       [Timestamp] idx: 3 (calls: 1, storage: 3)
                        [Balances] idx: 10 (calls: 6, storage: 6)
                      [Authorship] idx: 20 (calls: 1, storage: 4)
               [CollatorSelection] idx: 21 (calls: 5, storage: 6)
                         [Session] idx: 22 (calls: 2, storage: 8)
                       [XcmpQueue] idx: 30 (calls: 9, storage: 10)
                     [PolkadotXcm] idx: 31 (calls: 10, storage: 10)
                        [DmpQueue] idx: 33 (calls: 1, storage: 5)
                        [Multisig] idx: 41 (calls: 4, storage: 3)
                           [Proxy] idx: 42 (calls: 10, storage: 3)
                          [Assets] idx: 50 (calls: 25, storage: 5)
                         [Uniques] idx: 51 (calls: 24 -> 26, storage: 10 -> 11)
                                   [+] calls: setPrice, buyItem
                                   [+] storage: itemPriceOf

------------------------------ SUMMARY ------------------------------- 
⚠️ This filter is here to help spotting changes that should be reviewed carefully. 
⚠️ It catches only index changes, deletions and value decreases. 
## Deletions
 n/a 
## Index changes
 n/a 
## Decreases
 

 
----------------------------------------------------------------------

**Comment by EgorPopelyaev** [comment]
Metadata comparison:
Date: Mon Aug  8 12:42:43 UTC 2022
Reference: wss://statemint-rpc.polkadot.io
Target version: polkadot-parachain 0.9.270-38920db7b81
Chain: statemint-local
----------------------------------------------------------------------
              [Spec] name: statemint
                     spec_version: 9230 -> 9270
                     transaction_version: 7
          [Metadata] version: 14
           [Modules] num: 21
                          [System] idx: 0 (calls: 9, storage: 17)
                 [ParachainSystem] idx: 1 (calls: 4, storage: 21 -> 22)
                                   [+] storage: lastRelayChainBlockNumber
                       [Timestamp] idx: 3 (calls: 1, storage: 3)
                        [Balances] idx: 10 (calls: 6, storage: 6)
                      [Authorship] idx: 20 (calls: 1, storage: 4)
               [CollatorSelection] idx: 21 (calls: 5, storage: 6)
                         [Session] idx: 22 (calls: 2, storage: 8)
                       [XcmpQueue] idx: 30 (calls: 9, storage: 10)
                     [PolkadotXcm] idx: 31 (calls: 10, storage: 10)
                        [DmpQueue] idx: 33 (calls: 1, storage: 5)
                        [Multisig] idx: 41 (calls: 4, storage: 3)
                           [Proxy] idx: 42 (calls: 10, storage: 3)
                          [Assets] idx: 50 (calls: 25, storage: 5)
                         [Uniques] idx: 51 (calls: 24 -> 26, storage: 10 -> 11)
                                   [+] calls: setPrice, buyItem
                                   [+] storage: itemPriceOf

------------------------------ SUMMARY ------------------------------- 
⚠️ This filter is here to help spotting changes that should be reviewed carefully. 
⚠️ It catches only index changes, deletions and value decreases. 
## Deletions
 n/a 
## Index changes
 n/a 
## Decreases
 

 
----------------------------------------------------------------------

**Comment by EgorPopelyaev** [comment]
Metadata comparison:
Date: Mon Aug  8 11:54:09 UTC 2022
Reference: wss://westmint-rpc.polkadot.io
Target version: polkadot-parachain 0.9.270-38920db7b81
Chain: westmint-local
----------------------------------------------------------------------
              [Spec] name: westmint
                     spec_version: 9230 -> 9270
                     transaction_version: 7
          [Metadata] version: 14
           [Modules] num: 21
                          [System] idx: 0 (calls: 9, storage: 17)
                 [ParachainSystem] idx: 1 (calls: 4, storage: 21 -> 22)
                                   [+] storage: lastRelayChainBlockNumber
                       [Timestamp] idx: 3 (calls: 1, storage: 3)
                        [Balances] idx: 10 (calls: 6, storage: 6)
                      [Authorship] idx: 20 (calls: 1, storage: 4)
               [CollatorSelection] idx: 21 (calls: 5, storage: 6)
                         [Session] idx: 22 (calls: 2, storage: 8)
                       [XcmpQueue] idx: 30 (calls: 9, storage: 10)
                     [PolkadotXcm] idx: 31 (calls: 10, storage: 10)
                        [DmpQueue] idx: 33 (calls: 1, storage: 5)
                        [Multisig] idx: 41 (calls: 4, storage: 3)
                           [Proxy] idx: 42 (calls: 10, storage: 3)
                          [Assets] idx: 50 (calls: 25, storage: 5)
                         [Uniques] idx: 51 (calls: 24 -> 26, storage: 10 -> 11)
                                   [+] calls: setPrice, buyItem
                                   [+] storage: itemPriceOf

------------------------------ SUMMARY ------------------------------- 
⚠️ This filter is here to help spotting changes that should be reviewed carefully. 
⚠️ It catches only index changes, deletions and value decreases. 
## Deletions
 n/a 
## Index changes
 n/a 
## Decreases
 

 
----------------------------------------------------------------------

**Comment by EgorPopelyaev** [comment]
Metadata comparison:
Date: Mon Aug  8 14:41:33 UTC 2022
Reference: wss://rococo-statemint-rpc.polkadot.io
Target version: polkadot-parachain 0.9.270-38920db7b81
Chain: statemint-local
----------------------------------------------------------------------
              [Spec] name: statemine -> statemint
                     spec_version: 900 -> 9270
                     transaction_version: 6 -> 7
          [Metadata] version: 14
           [Modules] num: 21
                          [System] idx: 0 (calls: 9, storage: 17)
                 [ParachainSystem] idx: 1 (calls: 4, storage: 21 -> 22)
                                   [+] storage: lastRelayChainBlockNumber
                       [Timestamp] idx: 3 (calls: 1, storage: 3)
                        [Balances] idx: 10 (calls: 6, storage: 6)
                      [Authorship] idx: 20 (calls: 1, storage: 4)
               [CollatorSelection] idx: 21 (calls: 5, storage: 6)
                         [Session] idx: 22 (calls: 2, storage: 8)
                                       [setKeys] idx: 0 (args: 2)
                                                 (StatemineRuntimeSessionKeys, Bytes) -> (StatemintRuntimeSessionKeys, Bytes)
                                    [queuedKeys] type: Vec<(AccountId32,StatemineRuntimeSessionKeys)> -> Vec<(AccountId32,StatemintRuntimeSessionKeys)>
                                      [nextKeys] value: StatemineRuntimeSessionKeys -> StatemintRuntimeSessionKeys
                       [XcmpQueue] idx: 30 (calls: 9, storage: 10)
                     [PolkadotXcm] idx: 31 (calls: 10, storage: 10)
                        [DmpQueue] idx: 33 (calls: 1, storage: 5)
                        [Multisig] idx: 41 (calls: 4, storage: 3)
                           [Proxy] idx: 42 (calls: 10, storage: 3)
                                         [proxy] idx: 0 (args: 3)
                                                 (AccountId32, Option<StatemineRuntimeProxyType>, Call) -> (AccountId32, Option<StatemintRuntimeProxyType>, Call)
                                      [addProxy] idx: 1 (args: 3)
                                                 (AccountId32, StatemineRuntimeProxyType, u32) -> (AccountId32, StatemintRuntimeProxyType, u32)
                                   [removeProxy] idx: 2 (args: 3)
                                                 (AccountId32, StatemineRuntimeProxyType, u32) -> (AccountId32, StatemintRuntimeProxyType, u32)
                                     [anonymous] idx: 4 (args: 3)
                                                 (StatemineRuntimeProxyType, u32, u16) -> (StatemintRuntimeProxyType, u32, u16)
                                 [killAnonymous] idx: 5 (args: 5)
                                                 (AccountId32, StatemineRuntimeProxyType, u16, Compact<u32>, Compact<u32>) -> (AccountId32, StatemintRuntimeProxyType, u16, Compact<u32>, Compact<u32>)
                                [proxyAnnounced] idx: 9 (args: 4)
                                                 (AccountId32, AccountId32, Option<StatemineRuntimeProxyType>, Call) -> (AccountId32, AccountId32, Option<StatemintRuntimeProxyType>, Call)
                          [Assets] idx: 50 (calls: 25, storage: 5)
                         [Uniques] idx: 51 (calls: 23 -> 26, storage: 9 -> 11)
                                   [+] calls: freezeCollection, thawCollection, forceItemStatus, setCollectionMetadata, clearCollectionMetadata
                                       setCollectionMaxSupply, setPrice, buyItem
                                   [-] calls: freezeClass, thawClass, forceAssetStatus, setClassMetadata, clearClassMetadata
                                   [+] storage: itemPriceOf, collectionMaxSupply
                                         [class] value: PalletUniquesClassDetails -> PalletUniquesCollectionDetails
                                         [asset] value: PalletUniquesInstanceDetails -> PalletUniquesItemDetails
                               [classMetadataOf] value: PalletUniquesClassMetadata -> PalletUniquesCollectionMetadata
                            [instanceMetadataOf] value: PalletUniquesInstanceMetadata -> PalletUniquesItemMetadata

------------------------------ SUMMARY ------------------------------- 
⚠️ This filter is here to help spotting changes that should be reviewed carefully. 
⚠️ It catches only index changes, deletions and value decreases. 
## Deletions
 45: [-] calls: freezeClass, thawClass, forceAssetStatus, setClassMetadata, clearClassMetadata

## Index changes
 n/a 
## Decreases
 

 
----------------------------------------------------------------------

**Comment by chevdor** [comment]
The last run was a mix of rococo and statemint:
```
Reference: wss://rococo-statemint-rpc.polkadot.io
Target version: polkadot-parachain 0.9.270-38920db7b81
Chain: statemint-local
```

**Comment by bkontur** [comment]
### Run Extrinsic ordering jobs: 

**TODO: waiting for new RC tag**  @EgorPopelyaev 

**Statemine run:**
wss://statemine-rpc.polkadot.io
https://releases.parity.io/cumulus/**new-tag**/polkadot-parachain
statemine-local

**Statemint run:**
wss://statemint-rpc.polkadot.io
https://releases.parity.io/cumulus/**new-tag**/polkadot-parachain
statemint-local

**Westmint run:**
wss://westmint-rpc.polkadot.io
https://releases.parity.io/cumulus/**new-tag**/polkadot-parachain
westmint-local



### Manual comparison:

https://github.com/paritytech/cumulus/compare/v0.9.230...release-parachains-v9270

- [ ] **SignedExtensions:**

- statemine - no changes
- statemint - no changes
- westmint - no changes
- contracts/contract-rococo - no changes
- starters/seedling - no changes
- starters/shell - no changes
- testing/rococo-parachain - no changes 


- [ ] **Cumulus pallets:** - no changes

- [ ] **Substrate pallets:**

- TODO:

- [ ] **Polkadot pallets:**

- TODO:


**Open/Question:**
- is this change relevant for bumping `transaction_version`?
```
-		TransactionPayment: pallet_transaction_payment::{Pallet, Storage} = 11,
+		TransactionPayment: pallet_transaction_payment::{Pallet, Storage, Event<T>} = 11,
```

**Comment by bkontur** [comment]
I am checking "Extrinsic ordering" - see comment above: https://github.com/paritytech/cumulus/issues/1512#issuecomment-1209120936

1. I ran those 3 pipelines, and showed just few new storages + new calls, so I guess, no breaking changes, so no need to bump transaction_version, according to: https://github.com/paritytech/cumulus/pull/1516/files#diff-87479ac9ea16cec5ceafce00b3b049d7d5920cb663afae42901f20e7c4e6705dR80 

2. I manually checked repos (cumulus, substrate, polkadot) diff for all used pallets in statemine/statemint/westmint runtimes
    https://github.com/paritytech/cumulus/compare/v0.9.230...release-parachains-v9270
    https://github.com/paritytech/substrate/compare/polkadot-v0.9.23...polkadot-v0.9.27
    https://github.com/paritytech/polkadot/compare/v0.9.23...v0.9.27
 and I did not find any touched extrinsic call (changed arguments or calls), so I guess, no need to bump transaction_version

3 I saw some changes to storage: Vec -> BoundedVec
```
-	pub type Invulnerables<T: Config> = StorageValue<_, Vec<T::AccountId>, ValueQuery>;
+	pub type Invulnerables<T: Config> = StorageValue<_, BoundedVec<T::AccountId, T::MaxInvulnerables>, ValueQuery>;
```
or  removed GetDefault/ConstU32:
```
            b(super) type Metadata<T: Config<I>, I: 'static = ()> = StorageMap<
		_,
		Blake2_128Concat,
		T::AssetId,
		AssetMetadata<DepositBalanceOf<T, I>, BoundedVec<u8, T::StringLimit>>,
		ValueQuery,
-		GetDefault,
-		ConstU32<300_000>,StorageValue<_, BoundedVec<T::AccountId, T::MaxInvulnerables>, ValueQuery>;
```


@chevdor 
so, Will, please, I would like to ask you, what was the exact reason, that you changed `transaction_version: 6 -> 7` for statemine/statemint/westmint?
I am just trying to understand the process and your way of thinking or did I miss totally anything?
Thank you :)

**Comment by bkontur** [comment]
Proxy filters checked + following issue created https://github.com/paritytech/cumulus/issues/1531

**Comment by EgorPopelyaev** [comment]
Extrinsic ordering checks for the rc8 ⬇️

**Comment by EgorPopelyaev** [comment]
Metadata comparison:
Date: Wed Aug 10 15:37:35 UTC 2022
Reference: wss://statemine-rpc.polkadot.io
Target version: $BIN 0.9.270-ea404bfa9f2
Chain: statemine-local
----------------------------------------------------------------------
              [Spec] name: statemine
                     spec_version: 9230 -> 9270
                     transaction_version: 7
          [Metadata] version: 14
           [Modules] num: 21
                          [System] idx: 0 (calls: 9, storage: 17)
                 [ParachainSystem] idx: 1 (calls: 4, storage: 21 -> 22)
                                   [+] storage: lastRelayChainBlockNumber
                       [Timestamp] idx: 3 (calls: 1, storage: 3)
                        [Balances] idx: 10 (calls: 6, storage: 6)
                      [Authorship] idx: 20 (calls: 1, storage: 4)
               [CollatorSelection] idx: 21 (calls: 5, storage: 6)
                         [Session] idx: 22 (calls: 2, storage: 8)
                       [XcmpQueue] idx: 30 (calls: 9, storage: 10)
                     [PolkadotXcm] idx: 31 (calls: 10, storage: 10)
                        [DmpQueue] idx: 33 (calls: 1, storage: 5)
                        [Multisig] idx: 41 (calls: 4, storage: 3)
                           [Proxy] idx: 42 (calls: 10, storage: 3)
                          [Assets] idx: 50 (calls: 25, storage: 5)
                         [Uniques] idx: 51 (calls: 24 -> 26, storage: 10 -> 11)
                                   [+] calls: setPrice, buyItem
                                   [+] storage: itemPriceOf

------------------------------ SUMMARY ------------------------------- 
⚠️ This filter is here to help spotting changes that should be reviewed carefully. 
⚠️ It catches only index changes, deletions and value decreases. 
## Deletions
 n/a 
## Index changes
 n/a 
## Decreases
 

 
----------------------------------------------------------------------

**Comment by EgorPopelyaev** [comment]
Metadata comparison:
Date: Wed Aug 10 15:38:09 UTC 2022
Reference: wss://statemint-rpc.polkadot.io
Target version: $BIN 0.9.270-ea404bfa9f2
Chain: statemint-local
----------------------------------------------------------------------
              [Spec] name: statemint
                     spec_version: 9230 -> 9270
                     transaction_version: 7
          [Metadata] version: 14
           [Modules] num: 21
                          [System] idx: 0 (calls: 9, storage: 17)
                 [ParachainSystem] idx: 1 (calls: 4, storage: 21 -> 22)
                                   [+] storage: lastRelayChainBlockNumber
                       [Timestamp] idx: 3 (calls: 1, storage: 3)
                        [Balances] idx: 10 (calls: 6, storage: 6)
                      [Authorship] idx: 20 (calls: 1, storage: 4)
               [CollatorSelection] idx: 21 (calls: 5, storage: 6)
                         [Session] idx: 22 (calls: 2, storage: 8)
                       [XcmpQueue] idx: 30 (calls: 9, storage: 10)
                     [PolkadotXcm] idx: 31 (calls: 10, storage: 10)
                        [DmpQueue] idx: 33 (calls: 1, storage: 5)
                        [Multisig] idx: 41 (calls: 4, storage: 3)
                           [Proxy] idx: 42 (calls: 10, storage: 3)
                          [Assets] idx: 50 (calls: 25, storage: 5)
                         [Uniques] idx: 51 (calls: 24 -> 26, storage: 10 -> 11)
                                   [+] calls: setPrice, buyItem
                                   [+] storage: itemPriceOf

------------------------------ SUMMARY ------------------------------- 
⚠️ This filter is here to help spotting changes that should be reviewed carefully. 
⚠️ It catches only index changes, deletions and value decreases. 
## Deletions
 n/a 
## Index changes
 n/a 
## Decreases
 

 
----------------------------------------------------------------------

**Comment by EgorPopelyaev** [comment]
Metadata comparison:
Date: Wed Aug 10 15:38:41 UTC 2022
Reference: wss://westmint-rpc.polkadot.io
Target version: $BIN 0.9.270-ea404bfa9f2
Chain: westmint-local
----------------------------------------------------------------------
              [Spec] name: westmint
                     spec_version: 9230 -> 9270
                     transaction_version: 7
          [Metadata] version: 14
           [Modules] num: 21
                          [System] idx: 0 (calls: 9, storage: 17)
                 [ParachainSystem] idx: 1 (calls: 4, storage: 21 -> 22)
                                   [+] storage: lastRelayChainBlockNumber
                       [Timestamp] idx: 3 (calls: 1, storage: 3)
                        [Balances] idx: 10 (calls: 6, storage: 6)
                      [Authorship] idx: 20 (calls: 1, storage: 4)
               [CollatorSelection] idx: 21 (calls: 5, storage: 6)
                         [Session] idx: 22 (calls: 2, storage: 8)
                       [XcmpQueue] idx: 30 (calls: 9, storage: 10)
                     [PolkadotXcm] idx: 31 (calls: 10, storage: 10)
                        [DmpQueue] idx: 33 (calls: 1, storage: 5)
                        [Multisig] idx: 41 (calls: 4, storage: 3)
                           [Proxy] idx: 42 (calls: 10, storage: 3)
                          [Assets] idx: 50 (calls: 25, storage: 5)
                         [Uniques] idx: 51 (calls: 24 -> 26, storage: 10 -> 11)
                                   [+] calls: setPrice, buyItem
                                   [+] storage: itemPriceOf

------------------------------ SUMMARY ------------------------------- 
⚠️ This filter is here to help spotting changes that should be reviewed carefully. 
⚠️ It catches only index changes, deletions and value decreases. 
## Deletions
 n/a 
## Index changes
 n/a 
## Decreases
 

 
----------------------------------------------------------------------

**Comment by bkontur** [comment]
Westmint upgrade done: https://github.com/paritytech/devops/issues/1878

**Comment by EgorPopelyaev** [comment]
Closing as release is done https://github.com/paritytech/cumulus/releases/tag/parachains-v9270
