### ISSUE TITLE
Release Checklist - Client v0.9.290

### ISSUE THREAD

**Issue by EgorPopelyaev** [paritytech/cumulus#1637]
# Release Checklist - Client

See also #1611 

### Client Release

- [x] build a new `polkadot-parachain` binary and publish it to S3
- [x] new `polkadot-parachain` version has [run on the network](https://github.com/paritytech/cumulus/blob/master/docs/release.md#burn-in)
    without issue for at least 12h
- [x] a draft release has been created in the [Github Releases page](https://github.com/paritytech/cumulus/releases) with the relevant release-notes
- [x] the [build artifacts](https://github.com/paritytech/cumulus/blob/master/docs/release.md#build-artifacts) have been added to the
    draft-release.

---

Read more about the [release documentation](https://github.com/paritytech/cumulus/blob/master/docs/release.md).

**Comment by gilescope** [comment]
@BulatSaif

**Comment by gilescope** [comment]
new polkadot-parachain version has [run on the network](https://github.com/paritytech/cumulus/blob/master/docs/release.md#burn-in)
without issue for at least 12h - We had a panic but it seemed to be related to a malformed rpc call in the runtime so I think that's not something to worry about.

**Comment by chevdor** [comment]
@BulatSaif That's a valid suggestion, I would suggest opening a new issue for it.

**Comment by EgorPopelyaev** [comment]
Release is done https://github.com/paritytech/cumulus/releases/tag/v0.9.290
