### ISSUE TITLE
Automation of transaction_version bump

### ISSUE THREAD

**Issue by muharem** [paritytech/cumulus#1686]
## Problem
transaction_version bump during the release process is semi-automated, requires a manual launch of CI job and review of the report from an engineer, who is supposed to create a PR to bump a version if required. 

## Context
The transaction_version bump is part of the release checklist and must be performed to inform clients if the extrinsics, the extrinsic ordering, naming, the API to the runtime has changed. The process is semi-automated and requires some manpower (approximately up to 4 hours). 
As part of the release process automation initiative ([read more](https://github.com/paritytech/cumulus/issues/1657)) we try to improve the current process and bring more automation. 

## Tasks 
- [ ] extrinsic ordering check job creates PR with `transaction_version` bump if required and attaches the report to the PR description;
- [ ] the job sends a message to the matrix room with results of checks (with the PR if created);
- [ ] automatically trigger the job **when** TODO @muharem (when release branch is created?)

**Comment by chevdor** [comment]
This cannot be done currently but I am working on a solution.

Once I have the missing piece of code, I think we will just bump as required and make a PR automatically during the release process.

If the CI fails, you can subscribe to the notification from GH direclty.

**Comment by muharem** [comment]
@chevdor I would prefer the messages to the matrix, but we should probably bring this for the discussion.

I would love to have one channel where I can see all the progress of the current release.
Success runs of every step as well, with the links and relative information.

**Comment by xlc** [comment]
Every parachain needs this. Please make it reusable 🙏

**Comment by chevdor** [comment]
@xlc that's definitely the plan, keep an eye on the new `subwasm` versions.

**Comment by chevdor** [comment]
> @chevdor I would prefer the messages to the matrix

See https://github.com/paritytech/cumulus/pull/1727
