### ISSUE TITLE
Release Checklist for Client v0.9.320

### ISSUE THREAD

**Issue by EgorPopelyaev** [paritytech/cumulus#1843]
# Release Checklist - Client

### Client Release

- [x] build a new `polkadot-parachain` binary and publish it to S3
- [x] new `polkadot-parachain` version has [run on the network](../../docs/release.md#burnin)
    without issue for at least 12h
- [x] a draft release has been created in the [Github Releases page](https://github.com/paritytech/cumulus/releases) with the relevant release-notes
- [x] the [build artifacts](../../docs/release.md#build-artifacts) have been added to the
    draft-release.

---

Read more about the [release documentation](../../docs/release.md).

**Comment by EgorPopelyaev** [comment]
Burn-in requests:

- Westmint - #2096
- Statemine - #2097
- Statemint - #2098

**Comment by EgorPopelyaev** [comment]
v0.9.320 is released on 16.11.2022
