### ISSUE TITLE
Release Checklist for Client v0.9.420

### ISSUE THREAD

**Issue by EgorPopelyaev** [paritytech/cumulus#2506]
# Release Checklist - Client

### Client Release

- [x] build a new `polkadot-parachain` binary and publish it to S3
- [x] a draft release has been created in the [Github Releases page](https://github.com/paritytech/cumulus/releases) with the relevant release-notes
- [x] the [build artifacts](../../docs/release.md#build-artifacts) have been added to the
    draft-release.

---

Read more about the [release documentation](../../docs/release.md).

**Comment by BulatSaif** [comment]
Please hold off release until https://github.com/paritytech/cumulus/issues/2529 is fixed.
