### ISSUE TITLE
Release Checklist for Runtime v9430

### ISSUE THREAD

**Issue by EgorPopelyaev** [paritytech/cumulus#2654]
# Release Checklist - Runtimes

**All** following checks must be completed before publishing a new release.
The release process is owned and led by @paritytech/release-engineering team.
The checks marked with :crab: are meant to be checked by [a runtime engineer](https://github.com/paritytech/cumulus/issues/1761).

### Codebase
These checks should be performed on the codebase.

- [ ] the [`spec_version`](https://github.com/paritytech/cumulus/blob/master/docs/release.md#spec-version) has been incremented since the
    last release for any native runtimes from any existing use on public (non-private/test) networks
- [ ] :crab: previously [completed migrations](https://github.com/paritytech/cumulus/blob/master/docs/release.md#old-migrations-removed) are removed for any public (non-private/test) networks
- [ ] pallet and [extrinsic ordering](https://github.com/paritytech/cumulus/blob/master/docs/release.md#extrinsic-ordering--storage) as well as `SignedExtension`s have stayed
    the same. Bump `transaction_version` otherwise
- [ ] the [benchmarks](https://github.com/paritytech/ci_cd/wiki/Benchmarks:-cumulus) ran
- [ ] the weights have been updated for any modified runtime logic
- [ ] :crab: the new weights are sane, there are no significant (>50%) drops or rises with no reason
- [ ] :crab: XCM config is compatible with the configurations and versions of relevant interlocutors, like the Relay Chain.

### On the release branch

The following checks can be performed after we have forked off to the release-candidate branch or started an additional release candidate branch (rc-2, rc-3, etc)

- [ ] Verify [new migrations](https://github.com/paritytech/cumulus/blob/master/docs/release.md#new-migrations) complete successfully, and the
    runtime state is correctly updated for any public (non-private/test)
    networks
- [ ] Run [integration tests](https://github.com/paritytech/cumulus/blob/master/docs/release.md#integration-tests), and make sure they pass.
- [ ] Push runtime upgrade to Westmint and verify network stability
- [ ] Push runtime upgrade to Collectives and verify network stability

### Github

- [ ] Check that a draft release has been created at the [Github Releases page](https://github.com/paritytech/cumulus/releases) with relevant [release
    notes](https://github.com/paritytech/cumulus/blob/master/docs/release.md#release-notes)
- [ ] Check that [build artifacts](https://github.com/paritytech/cumulus/blob/master/docs/release.md#build-artifacts) have been added to the
    draft-release.

# Post release

- [ ] :crab: all commits (runtime version bumps, fixes) on this release branch have been merged back to master.

---

Read more about the [release documentation](https://github.com/paritytech/cumulus/blob/master/docs/release.md).

**Comment by EgorPopelyaev** [comment]
## bridge-hub-polkadot v9420 vs bridge-hub-polkadot v9430

<details>
<summary>
Comparison of the following runtimes:

```
specifications : bridge-hub-polkadot v9420
implementation : bridge-hub-polkadot v0
transaction    : v2
authoring      : v1
```

```
specifications : bridge-hub-polkadot v9430
implementation : bridge-hub-polkadot v0
transaction    : v2
authoring      : v1
```
**Compatible: true**
</summary>

```
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
[≠] pallet 0: System -> 1 change(s)
  - constants changes:
    [≠] Version: [ 76, 98, 114, 105, 100, 103, 101, 45, 104, 117, 98, 45, 112, 111, 108, 107, 97, 100, 111, 116, 76, 98, 114, 105, 100, 103, 101, 45, 104, 117, 98, 45, ... ]
        [Value([Changed(44, U8Change(204, 214))])]

SUMMARY:
- Compatible.......................: true
- Require transaction_version bump.: true

!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
```
</details>

**Comment by EgorPopelyaev** [comment]
## bridge-hub-kusama v9420 vs bridge-hub-kusama v9430

<details>
<summary>
Comparison of the following runtimes:

```
specifications : bridge-hub-kusama v9420
implementation : bridge-hub-kusama v0
transaction    : v3
authoring      : v1
```

```
specifications : bridge-hub-kusama v9430
implementation : bridge-hub-kusama v0
transaction    : v3
authoring      : v1
```
**Compatible: true**
</summary>

```
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
[≠] pallet 0: System -> 1 change(s)
  - constants changes:
    [≠] Version: [ 68, 98, 114, 105, 100, 103, 101, 45, 104, 117, 98, 45, 107, 117, 115, 97, 109, 97, 68, 98, 114, 105, 100, 103, 101, 45, 104, 117, 98, 45, 107, 117, ... ]
        [Value([Changed(40, U8Change(204, 214))])]

SUMMARY:
- Compatible.......................: true
- Require transaction_version bump.: true

!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
```
</details>

**Comment by EgorPopelyaev** [comment]
## bridge-hub-rococo v9420 vs bridge-hub-kusama v9430

<details>
<summary>
Comparison of the following runtimes:

```
specifications : bridge-hub-rococo v9420
implementation : bridge-hub-rococo v0
transaction    : v3
authoring      : v1
```

```
specifications : bridge-hub-kusama v9430
implementation : bridge-hub-kusama v0
transaction    : v3
authoring      : v1
```
**Compatible: true**
</summary>

```
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
[≠] pallet 0: System -> 2 change(s)
  - constants changes:
    [≠] SS58Prefix: [42, 0]
        [Value([Changed(0, U8Change(42, 2))])]
    [≠] Version: [ 68, 98, 114, 105, 100, 103, 101, 45, 104, 117, 98, 45, 114, 111, 99, 111, 99, 111, 68, 98, 114, 105, 100, 103, 101, 45, 104, 117, 98, 45, 114, 111, ... ]
        [Value([Changed(12, U8Change(114, 107)), Changed(13, U8Change(111, 117)), Changed(14, U8Change(99, 115)), Changed(15, U8Change(111, 97)), Changed(16, U8Change(99, 109)), Changed(17, U8Change(111, 97)), Changed(30, U8Change(114, 107)), Changed(31, U8Change(111, 117)), Changed(32, U8Change(99, 115)), Changed(33, U8Change(111, 97)), Changed(34, U8Change(99, 109)), Changed(35, U8Change(111, 97)), Changed(40, U8Change(204, 214))])]

[≠] pallet 10: Balances -> 1 change(s)
  - constants changes:
    [≠] ExistentialDeposit: [0, 202, 154, 59, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        [Value([Changed(0, U8Change(0, 85)), Changed(1, U8Change(202, 160)), Changed(2, U8Change(154, 252)), Changed(3, U8Change(59, 1))])]

[≠] pallet 41: Multisig -> 2 change(s)
  - constants changes:
    [≠] DepositBase: [220, 72, 233, 39, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        [Value([Changed(1, U8Change(72, 217)), Changed(2, U8Change(233, 28)), Changed(3, U8Change(39, 143)), Changed(4, U8Change(0, 1))])]
    [≠] DepositFactor: [160, 70, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        [Value([Changed(1, U8Change(70, 194)), Changed(2, U8Change(16, 162))])]

SUMMARY:
- Compatible.......................: true
- Require transaction_version bump.: true

!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
```

**Comment by EgorPopelyaev** [comment]
## contracts-rococo v9420 vs contracts-rococo v9430

<details>
<summary>
Comparison of the following runtimes:

```
specifications : contracts-rococo v9420
implementation : contracts-rococo v0
transaction    : v6
authoring      : v1
```

```
specifications : contracts-rococo v9430
implementation : contracts-rococo v0
transaction    : v6
authoring      : v1
```
**Compatible: true**
</summary>

```
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
[≠] pallet 0: System -> 1 change(s)
  - constants changes:
    [≠] Version: [ 64, 99, 111, 110, 116, 114, 97, 99, 116, 115, 45, 114, 111, 99, 111, 99, 111, 64, 99, 111, 110, 116, 114, 97, 99, 116, 115, 45, 114, 111, 99, 111, ... ]
        [Value([Changed(38, U8Change(204, 214))])]

[≠] pallet 40: Contracts -> 2 change(s)
  - events changes:
    [≠]  6: Called ( caller: T::AccountId, contract: T::AccountId, )  )
        [Signature(SignatureChange { args: [Changed(0, [Ty(StringChange("T::AccountId", "Origin<T>"))])] })]

  - constants changes:
    [≠] Schedule: [ 4, 0, 0, 0, 0, 1, 0, 0, 0, 4, 0, 0, 128, 0, 0, 0, 16, 0, 0, 0, 0, 16, 0, 0, 0, 1, 0, 0, 32, 0, 0, 0, ... ]
        [Value([Changed(48, U8Change(188, 195)), Changed(52, U8Change(73, 52)), Changed(53, U8Change(13, 14)), Changed(56, U8Change(5, 0)), Changed(60, U8Change(241, 243)), Changed(64, U8Change(225, 3)), Changed(65, U8Change(23, 24)), Changed(68, U8Change(53, 126)), Changed(72, U8Change(127, 255)), Changed(73, U8Change(9, 13)), Changed(76, U8Change(190, 161)), Changed(77, U8Change(18, 20)), Changed(80, U8Change(42, 4)), Changed(84, U8Change(111, 241)), Changed(85, U8Change(62, 64)), Changed(88, U8Change(89, 199)), Changed(89, U8Change(79, 77)), Changed(92, U8Change(219, 17)), Changed(96, U8Change(212, 96)), Changed(100, U8Change(93, 144)), Changed(104, U8Change(139, 149)), Changed(108, U8Change(243, 90)), Changed(109, U8Change(26, 28)), Changed(112, U8Change(191, 196)), Changed(116, U8Change(231, 233)), Changed(120, U8Change(187, 97)), Changed(121, U8Change(32, 30)), Changed(122, U8Change(201, 203)), Changed(124, U8Change(118, 110)), Changed(128, U8Change(30, 44)), Changed(132, U8Change(29, 36)), Changed(136, U8Change(212, 219)), Changed(140, U8Change(150, 162)), Changed(144, U8Change(104, 178)), Changed(148, U8Change(254, 7)), Changed(149, U8Change(2, 3)), Changed(152, U8Change(18, 84)), Changed(156, U8Change(252, 82)), Changed(157, U8Change(5, 7)), Changed(160, U8Change(29, 58)), Changed(164, U8Change(28, 59)), Changed(168, U8Change(161, 111)), Changed(172, U8Change(138, 153)), Changed(176, U8Change(34, 29)), Changed(180, U8Change(122, 111)), Changed(181, U8Change(6, 5)), Changed(184, U8Change(6, 3)), Changed(188, U8Change(38, 60)), Changed(192, U8Change(165, 193)), Changed(196, U8Change(159, 193)), Changed(200, U8Change(73, 92)), Changed(204, U8Change(17, 73)), Changed(205, U8Change(29, 28)), Changed(208, U8Change(68, 227)), Changed(209, U8Change(24, 23)), Changed(212, U8Change(200, 51)), Changed(213, U8Change(30, 29)), Changed(216, U8Change(192, 153)), Changed(220, U8Change(220, 234)), Changed(224, U8Change(64, 51)), Changed(228, U8Change(192, 226)), Changed(236, U8Change(170, 176)), Changed(240, U8Change(168, 158)), Changed(244, U8Change(50, 217)), Changed(245, U8Change(6, 5)), Changed(248, U8Change(167, 150)), Changed(252, U8Change(38, 202)), Changed(253, U8Change(191, 195)), Changed(254, U8Change(20, 19)), Changed(257, U8Change(22, 194)), Changed(258, U8Change(60, 29)), Changed(263, U8Change(178, 166)), Changed(264, U8Change(16, 27)), Changed(269, U8Change(14, 246)), Changed(270, U8Change(5, 79)), Changed(274, U8Change(254, 30)), Changed(275, U8Change(30, 56)), Changed(279, U8Change(14, 222)), Changed(280, U8Change(72, 219)), Changed(281, U8Change(20, 8)), Changed(283, U8Change(24, 12)), Changed(284, U8Change(14, 166)), Changed(285, U8Change(19, 29)), Changed(289, U8Change(254, 178)), Changed(290, U8Change(121, 163)), Changed(291, U8Change(88, 31)), Changed(294, U8Change(222, 38)), Changed(295, U8Change(34, 192)), Changed(296, U8Change(20, 88)), Changed(299, U8Change(86, 118)), Changed(300, U8Change(209, 242)), Changed(304, U8Change(162, 158)), Changed(305, U8Change(6, 206)), Changed(306, U8Change(21, 19)), Changed(309, U8Change(174, 186)), Changed(310, U8Change(8, 104)), Changed(311, U8Change(20, 19)), Changed(314, U8Change(214, 186)), Changed(315, U8Change(164, 85)), Changed(316, U8Change(81, 19)), Changed(318, U8Change(40, 24)), Changed(319, U8Change(158, 10)), Changed(320, U8Change(39, 171)), Changed(321, U8Change(8, 84)), Changed(323, U8Change(0, 56)), Changed(324, U8Change(154, 238)), Changed(325, U8Change(80, 206)), Changed(326, U8Change(16, 7)), Changed(328, U8Change(24, 0)), Changed(329, U8Change(45, 138)), Changed(330, U8Change(9, 32)), Changed(331, U8Change(0, 17)), Changed(332, U8Change(246, 0)), Changed(333, U8Change(200, 24)), Changed(334, U8Change(105, 77)), Changed(335, U8Change(0, 9)), Changed(336, U8Change(180, 0)), Changed(337, U8Change(197, 62)), Changed(338, U8Change(2, 143)), Changed(339, U8Change(0, 56)), Changed(340, U8Change(74, 0)), Changed(341, U8Change(150, 180)), Changed(342, U8Change(231, 213)), Changed(343, U8Change(252, 2)), Changed(344, U8Change(149, 0)), Changed(345, U8Change(121, 22)), Changed(346, U8Change(134, 194)), Changed(347, U8Change(28, 254)), Changed(348, U8Change(108, 253)), Changed(349, U8Change(0, 149)), Changed(350, U8Change(40, 121)), Changed(351, U8Change(42, 182)), Changed(352, U8Change(209, 174)), Changed(353, U8Change(211, 107)), Changed(356, U8Change(46, 218)), Changed(357, U8Change(114, 191)), Changed(358, U8Change(81, 210)), Changed(359, U8Change(30, 0)), Changed(360, U8Change(49, 40)), Changed(361, U8Change(39, 158)), Changed(362, U8Change(29, 245)), Changed(363, U8Change(9, 100)), Changed(364, U8Change(0, 30)), Changed(365, U8Change(54, 49)), Changed(366, U8Change(14, 39)), Changed(367, U8Change(14, 209)), Changed(368, U8Change(0, 11)), Changed(369, U8Change(28, 0)), Changed(370, U8Change(109, 122)), Changed(371, U8Change(11, 18)), Changed(372, U8Change(0, 14)), Changed(373, U8Change(14, 0)), Changed(374, U8Change(236, 28)), Changed(375, U8Change(59, 133)), Changed(376, U8Change(31, 11)), Changed(377, U8Change(149, 0)), Changed(378, U8Change(4, 54)), Changed(379, U8Change(105, 228)), Changed(380, U8Change(6, 63)), Changed(381, U8Change(0, 31)), Changed(382, U8Change(108, 149)), Changed(384, U8Change(194, 217)), Changed(385, U8Change(191, 6)), Changed(386, U8Change(173, 0)), Changed(387, U8Change(70, 165)), Changed(388, U8Change(73, 1)), Changed(389, U8Change(48, 4)), Changed(390, U8Change(194, 162)), Changed(391, U8Change(191, 5)), Changed(392, U8Change(50, 214)), Changed(393, U8Change(31, 70)), Changed(394, U8Change(133, 73)), Changed(395, U8Change(4, 48)), Changed(396, U8Change(41, 202)), Changed(397, U8Change(1, 29)), Changed(398, U8Change(4, 54)), Changed(399, U8Change(122, 31)), Changed(400, U8Change(198, 133)), Changed(401, U8Change(19, 4)), Changed(402, U8Change(7, 245)), Changed(403, U8Change(133, 1)), Changed(405, U8Change(141, 206)), Changed(406, U8Change(1, 39)), Changed(407, U8Change(4, 27)), Changed(408, U8Change(214, 7)), Changed(409, U8Change(225, 133)), Changed(410, U8Change(35, 4)), Changed(411, U8Change(7, 0)), Changed(412, U8Change(165, 4)), Changed(413, U8Change(4, 2)), Changed(414, U8Change(53, 65)), Changed(415, U8Change(11, 35)), Changed(416, U8Change(4, 7)), Changed(417, U8Change(34, 165)), Changed(418, U8Change(207, 4)), Changed(419, U8Change(69, 9)), Changed(420, U8Change(31, 11)), Changed(421, U8Change(165, 4)), Changed(422, U8Change(4, 10)), Changed(423, U8Change(109, 113)), Changed(424, U8Change(10, 68)), Changed(425, U8Change(4, 31)), Changed(426, U8Change(234, 165)), Changed(427, U8Change(198, 4)), Changed(428, U8Change(46, 161)), Changed(429, U8Change(38, 11)), Changed(430, U8Change(97, 4)), Changed(431, U8Change(39, 190)), Changed(432, U8Change(254, 156)), Changed(433, U8Change(182, 60)), Changed(434, U8Change(136, 38)), Changed(435, U8Change(109, 97)), Changed(436, U8Change(177, 39)), Changed(437, U8Change(42, 78)), Changed(438, U8Change(214, 168)), Changed(439, U8Change(240, 81)), Changed(440, U8Change(202, 111)), Changed(441, U8Change(84, 1)), Changed(442, U8Change(49, 43)), Changed(443, U8Change(40, 142)), Changed(444, U8Change(146, 163)), Changed(445, U8Change(243, 145)), Changed(446, U8Change(226, 86)), Changed(447, U8Change(67, 49)), Changed(448, U8Change(137, 40)), Changed(449, U8Change(80, 250)), Changed(450, U8Change(61, 6)), Changed(451, U8Change(9, 222)), Changed(452, U8Change(0, 66)), Changed(453, U8Change(182, 137)), Changed(454, U8Change(246, 80)), Changed(455, U8Change(95, 101)), Changed(456, U8Change(236, 9)), Changed(457, U8Change(85, 0)), Changed(458, U8Change(81, 94)), Changed(459, U8Change(106, 45)), Changed(460, U8Change(19, 93)), Changed(461, U8Change(71, 238)), Changed(462, U8Change(57, 85)), Changed(463, U8Change(41, 81)), Changed(464, U8Change(41, 250)), Changed(465, U8Change(229, 201)), Changed(466, U8Change(17, 176)), Changed(467, U8Change(0, 59)), Changed(468, U8Change(141, 41)), Changed(469, U8Change(20, 41)), Changed(470, U8Change(0, 125)), Changed(471, U8Change(34, 18)), Changed(472, U8Change(238, 0)), Changed(473, U8Change(34, 33)), Changed(474, U8Change(0, 21)), Changed(475, U8Change(32, 0)), Changed(476, U8Change(209, 206)), Changed(477, U8Change(60, 7)), Changed(478, U8Change(0, 35)), Changed(479, U8Change(222, 0)), Changed(480, U8Change(202, 32)), Changed(481, U8Change(44, 181)), Changed(482, U8Change(0, 61)), Changed(483, U8Change(32, 0)), Changed(484, U8Change(221, 26)), Changed(485, U8Change(48, 85)), Changed(486, U8Change(0, 45)), Changed(487, U8Change(126, 0)), Changed(488, U8Change(58, 32)), Changed(489, U8Change(25, 101)), Changed(490, U8Change(0, 49)), Changed(491, U8Change(32, 0)), Changed(492, U8Change(49, 234)), Changed(493, U8Change(14, 128)), Changed(494, U8Change(0, 25)), Changed(495, U8Change(6, 0)), Changed(496, U8Change(9, 32)), Changed(497, U8Change(25, 69)), Changed(498, U8Change(0, 14)), Changed(499, U8Change(32, 0)), Changed(500, U8Change(61, 150)), Changed(501, U8Change(14, 113)), Changed(502, U8Change(0, 25)), Changed(503, U8Change(194, 0)), Changed(504, U8Change(9, 32)), Changed(505, U8Change(194, 93)), Changed(506, U8Change(8, 14)), Changed(507, U8Change(53, 0)), Changed(508, U8Change(1, 6)), Changed(509, U8Change(162, 28)), Changed(510, U8Change(169, 247)), Changed(511, U8Change(48, 8)), Changed(512, U8Change(2, 53)), Changed(513, U8Change(168, 1)), Changed(514, U8Change(242, 178)), Changed(515, U8Change(220, 93)), Changed(516, U8Change(84, 58)), Changed(517, U8Change(11, 2)), Changed(518, U8Change(193, 168)), Changed(519, U8Change(1, 6)), Changed(520, U8Change(85, 66)), Changed(521, U8Change(73, 119)), Changed(522, U8Change(4, 11)), Changed(523, U8Change(174, 193)), Changed(524, U8Change(193, 1)), Changed(525, U8Change(9, 17)), Changed(526, U8Change(0, 73)), Changed(527, U8Change(12, 4)), Changed(528, U8Change(150, 102)), Changed(529, U8Change(222, 189)), Changed(530, U8Change(15, 9)), Changed(532, U8Change(160, 12)), Changed(533, U8Change(58, 54)), Changed(534, U8Change(114, 175)), Changed(535, U8Change(8, 15)), Changed(537, U8Change(12, 160)), Added(538, 194), Added(539, 192), Added(540, 8), Added(541, 0), Added(542, 12)])]

SUMMARY:
- Compatible.......................: true
- Require transaction_version bump.: true

!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
```
</details>

**Comment by EgorPopelyaev** [comment]
## test-parachain v9420 vs test-parachain v9430

<details>
<summary>
Comparison of the following runtimes:

```
specifications : test-parachain v9420
implementation : test-parachain v0
transaction    : v6
authoring      : v1
```

```
specifications : test-parachain v9430
implementation : test-parachain v0
transaction    : v6
authoring      : v1
```
**Compatible: true**
</summary>

```
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
[≠] pallet 0: System -> 1 change(s)
  - constants changes:
    [≠] Version: [ 56, 116, 101, 115, 116, 45, 112, 97, 114, 97, 99, 104, 97, 105, 110, 56, 116, 101, 115, 116, 45, 112, 97, 114, 97, 99, 104, 97, 105, 110, 1, 0, ... ]
        [Value([Changed(34, U8Change(204, 214))])]

[≠] pallet 31: Assets -> 5 change(s)
  - calls changes:
    [+] CallDesc { index: 29, name: "touch_other", signature: SignatureDesc { args: [ArgDesc { name: "id", ty: "T::AssetIdParameter" }, ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }] } }
    [+] CallDesc { index: 30, name: "refund_other", signature: SignatureDesc { args: [ArgDesc { name: "id", ty: "T::AssetIdParameter" }, ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }] } }
    [+] CallDesc { index: 31, name: "block", signature: SignatureDesc { args: [ArgDesc { name: "id", ty: "T::AssetIdParameter" }, ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }] } }

  - events changes:
    [+] EventDesc { index: 22, name: "Touched", signature: SignatureDesc { args: [ArgDesc { name: "asset_id", ty: "T::AssetId" }, ArgDesc { name: "who", ty: "T::AccountId" }, ArgDesc { name: "depositor", ty: "T::AccountId" }] } }
    [+] EventDesc { index: 23, name: "Blocked", signature: SignatureDesc { args: [ArgDesc { name: "asset_id", ty: "T::AssetId" }, ArgDesc { name: "who", ty: "T::AccountId" }] } }

SUMMARY:
- Compatible.......................: true
- Require transaction_version bump.: true

!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
```
</details>

**Comment by EgorPopelyaev** [comment]
## statemine v9420 vs statemine v9430

<details>
<summary>
Comparison of the following runtimes:

```
specifications : statemine v9420
implementation : statemine v0
transaction    : v13
authoring      : v1
```

```
specifications : statemine v9430
implementation : statemine v0
transaction    : v13
authoring      : v1
```
**Compatible: true**
</summary>

```
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
[≠] pallet 0: System -> 1 change(s)
  - constants changes:
    [≠] Version: [ 36, 115, 116, 97, 116, 101, 109, 105, 110, 101, 36, 115, 116, 97, 116, 101, 109, 105, 110, 101, 1, 0, 0, 0, 204, 36, 0, 0, 0, 0, 0, 0, ... ]
        [Value([Changed(24, U8Change(204, 214))])]

[≠] pallet 50: Assets -> 5 change(s)
  - calls changes:
    [+] CallDesc { index: 29, name: "touch_other", signature: SignatureDesc { args: [ArgDesc { name: "id", ty: "T::AssetIdParameter" }, ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }] } }
    [+] CallDesc { index: 30, name: "refund_other", signature: SignatureDesc { args: [ArgDesc { name: "id", ty: "T::AssetIdParameter" }, ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }] } }
    [+] CallDesc { index: 31, name: "block", signature: SignatureDesc { args: [ArgDesc { name: "id", ty: "T::AssetIdParameter" }, ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }] } }

  - events changes:
    [+] EventDesc { index: 22, name: "Touched", signature: SignatureDesc { args: [ArgDesc { name: "asset_id", ty: "T::AssetId" }, ArgDesc { name: "who", ty: "T::AccountId" }, ArgDesc { name: "depositor", ty: "T::AccountId" }] } }
    [+] EventDesc { index: 23, name: "Blocked", signature: SignatureDesc { args: [ArgDesc { name: "asset_id", ty: "T::AssetId" }, ArgDesc { name: "who", ty: "T::AccountId" }] } }

[≠] pallet 53: ForeignAssets -> 5 change(s)
  - calls changes:
    [+] CallDesc { index: 29, name: "touch_other", signature: SignatureDesc { args: [ArgDesc { name: "id", ty: "T::AssetIdParameter" }, ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }] } }
    [+] CallDesc { index: 30, name: "refund_other", signature: SignatureDesc { args: [ArgDesc { name: "id", ty: "T::AssetIdParameter" }, ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }] } }
    [+] CallDesc { index: 31, name: "block", signature: SignatureDesc { args: [ArgDesc { name: "id", ty: "T::AssetIdParameter" }, ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }] } }

  - events changes:
    [+] EventDesc { index: 22, name: "Touched", signature: SignatureDesc { args: [ArgDesc { name: "asset_id", ty: "T::AssetId" }, ArgDesc { name: "who", ty: "T::AccountId" }, ArgDesc { name: "depositor", ty: "T::AccountId" }] } }
    [+] EventDesc { index: 23, name: "Blocked", signature: SignatureDesc { args: [ArgDesc { name: "asset_id", ty: "T::AssetId" }, ArgDesc { name: "who", ty: "T::AccountId" }] } }

SUMMARY:
- Compatible.......................: true
- Require transaction_version bump.: true

!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
```
</details>

**Comment by EgorPopelyaev** [comment]
## westmint v9420 vs westmint v9430

<details>
<summary>
Comparison of the following runtimes:

```
specifications : westmint v9420
implementation : westmint v0
transaction    : v13
authoring      : v1
```

```
specifications : westmint v9430
implementation : westmint v0
transaction    : v13
authoring      : v1
```
**Compatible: true**
</summary>

```
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
[≠] pallet 0: System -> 1 change(s)
  - constants changes:
    [≠] Version: [ 32, 119, 101, 115, 116, 109, 105, 110, 116, 32, 119, 101, 115, 116, 109, 105, 110, 116, 1, 0, 0, 0, 204, 36, 0, 0, 0, 0, 0, 0, 52, 221, ... ]
        [Value([Changed(22, U8Change(204, 214))])]

[≠] pallet 10: Balances -> 1 change(s)
  - constants changes:
    [≠] MaxHolds: [0; 4]
        [Value([Changed(0, U8Change(0, 1))])]

[≠] pallet 50: Assets -> 5 change(s)
  - calls changes:
    [+] CallDesc { index: 29, name: "touch_other", signature: SignatureDesc { args: [ArgDesc { name: "id", ty: "T::AssetIdParameter" }, ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }] } }
    [+] CallDesc { index: 30, name: "refund_other", signature: SignatureDesc { args: [ArgDesc { name: "id", ty: "T::AssetIdParameter" }, ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }] } }
    [+] CallDesc { index: 31, name: "block", signature: SignatureDesc { args: [ArgDesc { name: "id", ty: "T::AssetIdParameter" }, ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }] } }

  - events changes:
    [+] EventDesc { index: 22, name: "Touched", signature: SignatureDesc { args: [ArgDesc { name: "asset_id", ty: "T::AssetId" }, ArgDesc { name: "who", ty: "T::AccountId" }, ArgDesc { name: "depositor", ty: "T::AccountId" }] } }
    [+] EventDesc { index: 23, name: "Blocked", signature: SignatureDesc { args: [ArgDesc { name: "asset_id", ty: "T::AssetId" }, ArgDesc { name: "who", ty: "T::AccountId" }] } }

[≠] pallet 53: ForeignAssets -> 5 change(s)
  - calls changes:
    [+] CallDesc { index: 29, name: "touch_other", signature: SignatureDesc { args: [ArgDesc { name: "id", ty: "T::AssetIdParameter" }, ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }] } }
    [+] CallDesc { index: 30, name: "refund_other", signature: SignatureDesc { args: [ArgDesc { name: "id", ty: "T::AssetIdParameter" }, ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }] } }
    [+] CallDesc { index: 31, name: "block", signature: SignatureDesc { args: [ArgDesc { name: "id", ty: "T::AssetIdParameter" }, ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }] } }

  - events changes:
    [+] EventDesc { index: 22, name: "Touched", signature: SignatureDesc { args: [ArgDesc { name: "asset_id", ty: "T::AssetId" }, ArgDesc { name: "who", ty: "T::AccountId" }, ArgDesc { name: "depositor", ty: "T::AccountId" }] } }
    [+] EventDesc { index: 23, name: "Blocked", signature: SignatureDesc { args: [ArgDesc { name: "asset_id", ty: "T::AssetId" }, ArgDesc { name: "who", ty: "T::AccountId" }] } }

[+] id: 54 - new pallet: NftFractionalization
SUMMARY:
- Compatible.......................: true
- Require transaction_version bump.: true

!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
```
</details>

**Comment by EgorPopelyaev** [comment]
No `transaction_version` bump is needed

**Comment by gilescope** [comment]
All the integration tests pass.

**Comment by gilescope** [comment]
I've diffed all the Xcm and lib.rs for the relay chains and parachains. Nothing unexpected found.

**Comment by EgorPopelyaev** [comment]
Release is out
