### ISSUE TITLE
Statemine v5 Release Checklist

### ISSUE THREAD

**Issue by apopiak** [paritytech/cumulus#661]
# Release Checklist

This is the release checklist for Statemine v5. **All** following
checks should be completed before publishing a new release of the
Statemine runtime. The current release candidate can be
checked out with `git checkout release-statemine-v5`

### Runtime Releases

These checks should be performed on the codebase.

- [x] Verify [`spec_version`](#spec-version) has been incremented since the
    last release for any native runtimes from any existing use on public
    (non-private/test) networks.
- [x] Verify previously [completed migrations](#old-migrations-removed) are
    removed for any public (non-private/test) networks.
- [x] Verify pallet and [extrinsic ordering](#extrinsic-ordering) as well as `SignedExtension`s have stayed
    the same. Bump `transaction_version` if not.
  - Changed transaction payment (https://github.com/paritytech/cumulus/pull/488)  -> `SignedExtra` changed --> bumping `transaction_version`
- [x] Verify new extrinsics have been correctly whitelisted/blacklisted for
    [proxy filters](#proxy-filtering).
- [x] Verify [benchmarks](#benchmarks) have been updated for any modified
    runtime logic. @NachoPal 
  - [x] Verify the weights are up-to-date.
- [x] Verify that the various pieces of XCM config are sane.

The following checks can be performed after we have forked off to the release-
candidate branch or started an additional release candidate branch (rc-2, rc-3, etc)

- [x] Verify [new migrations](#new-migrations) complete successfully, and the
    runtime state is correctly updated for any public (non-private/test)
    networks. (There should be no migrations for this release.)
- [x] Verify [Polkadot JS API](#polkadot-js) are up to date with the latest
    runtime changes.
- [x] Push runtime upgrade to Westmint and verify network stability.

### All Releases

- [x] Check that the new polkadot-collator versions have [run on the network](#burn-in)
    without issue.
- [x] Check that a draft release has been created at
    https://github.com/paritytech/cumulus/releases with relevant [release
    notes](#release-notes)
- [x] Check that [build artifacts](#build-artifacts) have been added to the
    draft-release

### Burn In

Ensure that Parity DevOps has run the new release on Westmint and Statemine collators for 12h prior to publishing the release.

### Build Artifacts

Add any necessary assets to the release. They should include:

- Linux binary
- GPG signature of the Linux binary
- SHA256 of binary
- Source code
- Wasm binaries of any runtimes

### Release notes

The release notes should list:

- The priority of the release (i.e., how quickly users should upgrade) - this is
    based on the max priority of any *client* changes.
- Which native runtimes and their versions are included
- The proposal hashes of the runtimes as built with
    [srtool](https://github.com/paritytech/srtool)
- Any changes in this release that are still awaiting audit

The release notes may also list:

- Free text at the beginning of the notes mentioning anything important
    regarding this release
- Notable changes separated into sections.

### Spec Version

A runtime upgrade must bump the spec number. This may follow a pattern with the
client release (e.g. runtime v12 corresponds to v0.8.12, even if the current
runtime is not v11).

### Old Migrations Removed

Previous `on_runtime_upgrade` functions from old upgrades should be removed.

### New Migrations

Ensure that any migrations that are required due to storage or logic changes
are included in the `on_runtime_upgrade` function of the appropriate pallets.

### Extrinsic Ordering

Offline signing libraries depend on a consistent ordering of call indices and
functions. Compare the metadata of the current and new runtimes and ensure that
the `module index, call index` tuples map to the same set of functions. In case
of a breaking change, increase `transaction_version`.

To verify the order has not changed:

1. Download the latest release-candidate binary from the draft-release
on Github.
  - [ ] Add link to release candidate binary
2. Run the release-candidate binary using a local chain:
  - [ ] Add polkadot-collator invocation for Statemine and Westmint here. @chevdor 
3. Use [`polkadot-js-tools`](https://github.com/polkadot-js/tools) to compare
the metadata:
  - Todo: Add Statemine endpoint in template here
4. Things to look for in the output are lines like:
  - `[Identity] idx 28 -> 25 (calls 15)` - indicates the index for `Identity` has changed
  - `[+] Society, Recovery` - indicates the new version includes 2 additional modules/pallets.
  - If no indices have changed, every modules line should look something like `[Identity] idx 25 (calls 15)`

Note: Adding new functions to the runtime does not constitute a breaking change
as long as they are added to the end of a pallet (i.e., does not break any
other call index).

### Proxy Filtering

The runtime contains proxy filters that map proxy types to allowable calls. If
the new runtime contains any new calls, verify that the proxy filters are up to
date to include them.

### Benchmarks

Until #631 is done, running the benchmarks is a manual process:
1. Connect to the bechmarking machine `149.202.69.202`
2. Make sure no one else is using the machine with `htop check`
3. Pull in the branch of Cumulus that has the version of Statemine you want to release
4. Recompile `cargo build --features runtime-benchmarks`
5. From the root directory run `nohup ./scripts/benchmarks.sh &` (it will take quite a few hours)
6. Checkout in your local machine to the branch of cumulus that has the version of Statemine you want to release
7. `scp` from the host to your local machine the weights for Statemine, Westmint and Statemint you'll find in:
   - `/polkadot-parachains/statemine/src/weights`
   - `/polkadot-parachains/westmint/src/weights`
   - `/polkadot-parachains/statemint/src/weights`
8. Commit the changes in your local and create a PR

### Polkadot JS

Ensure that a release of [Polkadot JS API](https://github.com/polkadot-js/api/) contains any new types or
interfaces necessary to interact with the new runtime.

**Comment by apopiak** [comment]
we released :tada: https://github.com/paritytech/cumulus/releases/tag/statemine-v5.0.0
